import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {createAccess,DISCORD_OWNER} from '../server/access.js';
async function fixture(t,user=DISCORD_OWNER){const parent=path.resolve('.local/test-fixtures');await fs.mkdir(parent,{recursive:true});const directory=await fs.mkdtemp(path.join(parent,'access-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));let time=100000;const calls=[];const options={directory,origin:'http://127.0.0.1:4317',now:()=>time,encrypt:async value=>Buffer.from(value).toString('base64'),decrypt:async value=>Buffer.from(value,'base64').toString(),fetcher:async(url,options)=>{calls.push(url);return {ok:true,json:async()=>url.endsWith('/token')?{access_token:'private-access-token',refresh_token:'private-refresh-token',expires_in:120}:{id:user,username:'test',global_name:'Alex',avatar:'a_0123456789abcdef'}}}};const access=await createAccess(options);await access.configure('private-client-secret');return {access,options,calls,advance:()=>{time+=130000}};}
test('Discord owner session survives restart and refreshes after expiry without reopening browser',async t=>{const f=await fixture(t);const url=new URL(f.access.begin().url);await f.access.callback({state:url.searchParams.get('state'),code:'test-code'});assert.equal(f.access.allowed(),true);assert.equal(f.access.publicState().user.displayName,'Alex');assert.match(f.access.publicState().user.avatarUrl,/cdn\.discordapp\.com\/avatars\/.*\.gif\?size=128$/);assert.ok(!JSON.stringify(f.access.publicState()).includes('private-'));const disk=await fs.readFile(path.join(f.options.directory,'discord-access.json'),'utf8');assert.ok(!disk.includes('private-'));const restored=await createAccess(f.options);assert.equal(restored.allowed(),false);assert.equal(await restored.ensure(),true);f.advance();assert.equal(await restored.ensure(),true);assert.equal(f.calls.filter(url=>url.endsWith('/token')).length,2);});
test('Discord refuses other accounts and callback state replay',async t=>{const f=await fixture(t,'another-user');const url=new URL(f.access.begin().url);const input={state:url.searchParams.get('state'),code:'test-code'};await assert.rejects(f.access.callback(input),/pas autorisé/);assert.equal(f.access.allowed(),false);await assert.rejects(f.access.callback(input),/expirée ou invalide/);});
test('Discord rejects CSRF state before contacting token endpoint',async t=>{const f=await fixture(t);f.access.begin();await assert.rejects(f.access.callback({state:'bad',code:'test'}));assert.equal(f.calls.length,0);});
import {createApp} from '../server/index.js';
test('locked dashboard API does not disclose settings or accept project actions',async t=>{
 const parent=path.resolve('.local/test-fixtures');await fs.mkdir(parent,{recursive:true});const directory=await fs.mkdtemp(path.join(parent,'access-api-'));const backend=await createApp({dataDir:directory,port:4329});const server=await new Promise(resolve=>{const value=backend.app.listen(4329,'127.0.0.1',()=>resolve(value));});t.after(async()=>{backend.close();server.closeAllConnections();await new Promise(r=>server.close(r));await backend.workspace.flush();await fs.rm(directory,{recursive:true,force:true});});
 const status=await fetch('http://127.0.0.1:4329/api/access/status').then(r=>r.json());assert.equal(status.authorized,false);assert.equal(status.settings,undefined);for(const route of ['bootstrap','settings','projects','state']){const response=await fetch('http://127.0.0.1:4329/api/'+route,{headers:{'X-Panel-Token':status.token}});assert.equal(response.status,401);}
 const response=await fetch('http://127.0.0.1:4329/api/projects/example/action',{method:'POST',headers:{'Content-Type':'application/json','X-Panel-Token':status.token},body:JSON.stringify({action:'release'})});assert.equal(response.status,401);
});
