import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import net from 'node:net';
import { createApp, APP_ROOT } from '../server/index.js';

test('local API integration: session token, origin, content type, configuration and static isolation', async t => {
  const parent = path.join(APP_ROOT, '.local', 'test-fixtures');
  await fs.mkdir(parent, { recursive: true });
  const directory = await fs.mkdtemp(path.join(parent, 'api-'));
  const probe = net.createServer();
  await new Promise(resolve => probe.listen(0, '127.0.0.1', resolve));
  const port = probe.address().port;
  await new Promise(resolve => probe.close(resolve));
  const { app, close, workspace } = await createApp({requireAuth:false, port, dataDir: directory });
  const server = app.listen(port, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(async () => { close(); await workspace.flush(); await new Promise(resolve => server.close(resolve)); assert.equal(path.dirname(path.resolve(directory)), parent); await fs.rm(directory, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${port}`;
  const boot = await fetch(`${base}/api/bootstrap`);
  assert.equal(boot.status, 200);
  const bootstrap = await boot.json();
  assert.equal(bootstrap.app, 'lestitcheur-control');
  assert.equal(bootstrap.settings.pteroKey, undefined);
  assert.equal(bootstrap.settings.spotifyTokens, undefined);
  assert.equal((await fetch(`${base}/api/settings`)).status, 403);
  assert.equal((await fetch(`${base}/api/pterodactyl/abc123/console`)).status, 403);
  assert.equal((await fetch(`${base}/api/bootstrap`, { headers: { Origin: 'https://evil.example' } })).status, 403);
  assert.equal((await fetch(`${base}/api/bootstrap`, { headers: { 'Sec-Fetch-Site': 'cross-site' } })).status, 403);
  const headers = { 'X-Panel-Token': bootstrap.token, 'Content-Type': 'application/json' };
  assert.equal((await fetch(`${base}/api/pterodactyl/abc123/console`, { headers: { ...headers, Origin: 'https://evil.example' } })).status, 403);
  assert.equal((await fetch(`${base}/api/pterodactyl/${encodeURIComponent('../outside')}/console`, { headers })).status, 400);
  assert.equal((await fetch(`${base}/api/settings`, { headers })).status, 200);
  const noJson = await fetch(`${base}/api/settings`, { method: 'POST', headers: { 'X-Panel-Token': bootstrap.token }, body: 'x=1' });
  assert.equal(noJson.status, 415);
  const wrongOrigin = await fetch(`${base}/api/settings`, { method: 'POST', headers: { ...headers, Origin: 'https://evil.example' }, body: '{}' });
  assert.equal(wrongOrigin.status, 403);
  const invalidUrl = await fetch(`${base}/api/settings`, { method: 'POST', headers, body: JSON.stringify({ pteroUrl: 'ftp://panel.example.com' }) });
  assert.equal(invalidUrl.status, 400);
  const settings = await fetch(`${base}/api/settings`, { method: 'POST', headers, body: JSON.stringify({ projectsRoot: directory, pteroUrl: 'http://192.168.1.10:8080/' }) });
  assert.equal(settings.status, 200);
  assert.equal((await settings.json()).pteroUrl, 'http://192.168.1.10:8080');
  assert.equal((await (await fetch(`${base}/api/settings`, { headers })).json()).pteroUrl, 'http://192.168.1.10:8080');
  const list = await fetch(`${base}/api/projects`, { headers });
  assert.deepEqual((await list.json()).map(p=>p.name), ['projects']);
  const traversal = await fetch(`${base}/api/projects/${encodeURIComponent('../outside')}/action`, { method: 'POST', headers, body: JSON.stringify({ action: 'delete', confirm: '../outside' }) });
  assert.equal(traversal.status, 400);
  const secretFile = await fetch(`${base}/.local/settings.json`);
  assert.doesNotMatch(await secretFile.text(), /"projectsRoot"/);
  const oversized = await fetch(`${base}/api/settings`, { method: 'POST', headers, body: JSON.stringify({ text: 'x'.repeat(26000) }) });
  assert.equal(oversized.status, 400);
});
