import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {EventEmitter} from 'node:events';
import {createWorkspace} from '../server/workspace.js';import {snapshot,gitMutation,gitRun,secretFindings} from '../server/git-worktree.js';import {databaseName} from '../server/mysql-admin.js';import {certificate} from '../server/operations.js';
async function fixture(t){const base=path.resolve('.local/test-fixtures');await fs.mkdir(base,{recursive:true});const dir=await fs.mkdtemp(path.join(base,'ops-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return dir;}
test('metric alerts fire only on threshold crossings and persist with notifications',async t=>{const dir=await fixture(t),w=await createWorkspace(dir);await w.samples([{id:'local',name:'PC',cpu:95,memory:40,disk:50}]);await w.samples([{id:'local',name:'PC',cpu:96,memory:40,disk:50}]);assert.equal(w.get().notifications.length,1);await w.samples([{id:'local',name:'PC',cpu:30,memory:40,disk:50}]);assert.equal(w.get().notifications.length,2);const id=w.get().notifications[0].id;await w.readOne(id);assert.equal(w.get().notifications[0].read,true);await w.externalNotifications([{key:'event:1',message:'New release',source:'github'}]);await w.externalNotifications([{key:'event:1',message:'New release',source:'github'}]);assert.equal(w.get().notifications.length,3);await w.flush();assert.equal((await createWorkspace(dir)).get().samples.local.length,3);await assert.rejects(w.preferences({thresholds:{cpu:101,memory:90,disk:90}}));});
test('domain expiry and invalid certificates produce deduplicated alerts',async t=>{const w=await createWorkspace(await fixture(t)),item={domain:'example.com',expiresAt:new Date(Date.now()+86400000).toISOString(),certificate:{valid:false,error:'TLS error',expiresAt:null}};await w.domainHealth([item]);await w.domainHealth([item]);assert.equal(w.get().notifications.length,2);});
test('Git commit rejects stale files, detects secrets and switch preserves local work',async t=>{const cwd=await fixture(t);await gitRun(cwd,['init']);await gitRun(cwd,['config','user.name','Fixture']);await gitRun(cwd,['config','user.email','fixture@example.invalid']);await fs.writeFile(path.join(cwd,'a.txt'),'first');const first=await snapshot(cwd);await fs.writeFile(path.join(cwd,'a.txt'),'second');await assert.rejects(gitMutation(cwd,{operation:'commit',message:'test',fingerprint:first.fingerprint}),/changé/);await gitMutation(cwd,{operation:'commit',message:'first',fingerprint:(await snapshot(cwd)).fingerprint});await gitRun(cwd,['branch','next']);await fs.writeFile(path.join(cwd,'a.txt'),'third');await assert.rejects(gitMutation(cwd,{operation:'switch',branch:'next',fingerprint:(await snapshot(cwd)).fingerprint}),/Commite/);await fs.writeFile(path.join(cwd,'.env'),'PASSWORD=example');assert.equal((await snapshot(cwd)).findings[0].kind,'Fichier sensible');assert.deepEqual(secretFindings('test.txt','safe'),[]);});
test('MySQL rejects system databases and injection before execution',()=>{for(const name of ['mysql','sys','performance_schema','information_schema','db;DROP TABLE x','../db',''])assert.throws(()=>databaseName(name));assert.equal(databaseName('fivem_db'),'fivem_db');});
test('TLS failures resolve as unavailable rather than successful certificates',async()=>{const connect=()=>{const socket=new EventEmitter();socket.setTimeout=()=>{};socket.destroy=()=>{};queueMicrotask(()=>socket.emit('error',Error('offline')));return socket;};assert.equal((await certificate('example.com',connect)).valid,false);assert.throws(()=>certificate('localhost:443',connect));});
import {createProjects} from '../server/projects.js';import {createJobs} from '../server/jobs.js';
test('release preflight is required and invalidated by changed artifacts',async t=>{const root=await fixture(t),cwd=path.join(root,'project');await fs.mkdir(cwd);await fs.mkdir(path.join(cwd,'node_modules'));await fs.mkdir(path.join(cwd,'release'));await fs.writeFile(path.join(cwd,'.gitignore'),'node_modules/\nrelease/\n');await fs.writeFile(path.join(cwd,'package.json'),JSON.stringify({version:'1.0.0',scripts:{test:'node verify.cjs',build:'node verify.cjs'}}));await fs.writeFile(path.join(cwd,'verify.cjs'),"console.log('fixture passed')");for(const [name,value] of [['Demo-Setup-1.0.0.exe','fixture'],['Demo-Setup-1.0.0.exe.blockmap','map'],['latest.yml','version: 1.0.0\npath: Demo-Setup-1.0.0.exe\n']])await fs.writeFile(path.join(cwd,'release',name),value);await gitRun(cwd,['init']);await gitRun(cwd,['config','user.name','Fixture']);await gitRun(cwd,['config','user.email','fixture@example.invalid']);await gitRun(cwd,['add','.']);await gitRun(cwd,['commit','-m','fixture']);await gitRun(cwd,['remote','add','origin','https://github.com/example/fixture.git']);const jobs=createJobs(),projects=createProjects({get:()=>({projectsRoot:root})},jobs,root);const before=await projects.releasePlan('project');assert.equal(before.verified,false);await assert.rejects(projects.action('project','release',{fingerprint:before.fingerprint}),/vérification/);const {jobId}=await projects.action('project','preflight',{});while(jobs.find(jobId).status==='running')await new Promise(r=>setTimeout(r,50));assert.equal(jobs.find(jobId).status,'success',jobs.find(jobId).output);assert.equal((await projects.releasePlan('project')).verified,true);await fs.writeFile(path.join(cwd,'release','Demo-Setup-1.0.0.exe'),'changed');assert.equal((await projects.releasePlan('project')).verified,false);});
import {workspaceRoutes} from '../server/workspace-routes.js';
test('session waits for stack before editor and rejects missing project before starting services',async t=>{const w=await createWorkspace(await fixture(t));const mode=await w.save('sessions',{name:'FiveM',project:'fixture',stack:true,editor:true,terminal:true});const routes=new Map(),app={get(){},post(route,handler){routes.set(route,handler);}},events=[],jobs=createJobs();const monitor=workspaceRoutes(app,{workspace:w,settings:{get:()=>({})},services:{start(){return jobs.create('Stack fixture',async()=>{await new Promise(r=>setTimeout(r,20));events.push('stack');});}},projects:{action:async()=>events.push('editor')},jobs,ptero:{},cloud:{},music:()=>({}),terminalRunning:()=>false,consoles:{}});t.after(()=>monitor.close());let response;await routes.get('/api/workspace/sessions/:id/run')({params:{id:mode.id}},{json(value){response=value;}});while(jobs.find(response.jobId).status==='running')await new Promise(r=>setTimeout(r,50));assert.equal(jobs.find(response.jobId).status,'success');assert.deepEqual(events,['stack','editor']);assert.equal(response.terminal,true);const invalid=await w.save('sessions',{name:'Invalid',stack:true,editor:true});await assert.rejects(routes.get('/api/workspace/sessions/:id/run')({params:{id:invalid.id}},{json(){}}),/Choisis un projet/);assert.deepEqual(events,['stack','editor']);});

test('Git add and version commit remain separate and preserve unstaged edits',async t=>{
 const cwd=await fixture(t);await gitRun(cwd,['init']);await gitRun(cwd,['config','user.name','Fixture']);await gitRun(cwd,['config','user.email','fixture@example.invalid']);
 await fs.writeFile(path.join(cwd,'.gitignore'),'ignored.txt\n');await fs.writeFile(path.join(cwd,'ignored.txt'),'ignore me');await fs.writeFile(path.join(cwd,'a.txt'),'staged');
 const mutate=async input=>gitMutation(cwd,{...input,fingerprint:(await snapshot(cwd)).fingerprint});
 await assert.rejects(mutate({operation:'commit-version',version:'2.9.0'}),/Aucun fichier/);
 await mutate({operation:'stage'});assert.ok(!(await gitRun(cwd,['ls-files'])).includes('ignored.txt'));
 await fs.writeFile(path.join(cwd,'a.txt'),'not staged');
 await assert.rejects(mutate({operation:'commit-version',version:'2.9.0; bad'}),/version valide/);
 await mutate({operation:'commit-version',version:'2.9.0'});
 assert.equal(await gitRun(cwd,['log','-1','--format=%s']),'MAJ 2.9.0');assert.equal(await gitRun(cwd,['show','HEAD:a.txt']),'staged');assert.ok((await snapshot(cwd)).status.includes('a.txt'));
 const first=await snapshot(cwd);await gitRun(cwd,['add','.']);await assert.rejects(gitMutation(cwd,{operation:'commit-version',version:'2.9.1',fingerprint:first.fingerprint}),/changé/);
});

test('version commit checks staged secrets even when the working copy is clean',async t=>{
 const cwd=await fixture(t);await gitRun(cwd,['init']);await fs.writeFile(path.join(cwd,'key.txt'),['-----BEGIN', 'PRIVATE KEY-----'].join(' '));await gitRun(cwd,['add','.']);await fs.writeFile(path.join(cwd,'key.txt'),'safe');
 await assert.rejects(gitMutation(cwd,{operation:'commit-version',version:'1.0.0',fingerprint:(await snapshot(cwd)).fingerprint}),/sensible/);
});


test('security test fixtures do not look like embedded private keys in source',async()=>{
 const source=await fs.readFile(new URL('./operations.test.js',import.meta.url),'utf8');
 assert.deepEqual(secretFindings('tests/operations.test.js',source),[]);
 const marker=['-----BEGIN','PRIVATE KEY-----'].join(' ');
 assert.ok(secretFindings('key.txt',marker).includes('Clé privée'));
});
