import fs from 'node:fs/promises';
import {createWriteStream} from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import mysql from 'mysql2/promise';
import {seal,unseal} from './platform.js';
import {resolveLaragon} from './laragon.js';
export function databaseName(name){if(typeof name!=='string'||!/^[\w$-]{1,64}$/.test(name)||['mysql','sys','performance_schema','information_schema'].includes(name.toLowerCase()))throw Error('Choisis une base utilisateur valide.');return name;}
export async function createMysql({directory,settings,jobs}){
 const file=path.join(directory,'mysql-access.json'),backups=path.join(directory,'mysql-backups');let config={user:'root',password:''};try{config=JSON.parse(await unseal(await fs.readFile(file,'utf8')));}catch(e){if(e.code!=='ENOENT')throw Error('Identifiants MySQL illisibles.');}
 const connection=()=>mysql.createConnection({host:'127.0.0.1',port:settings.get().mysqlPort,user:config.user,password:config.password,connectTimeout:5000});
 async function client(executable,database,input,output){const c=settings.get();const laragon=c.mysqlMode==='laragon'?await resolveLaragon(c.laragonRoot,c.laragonVersion):null;const bin=laragon?path.dirname(laragon.exe):path.dirname(c.mysqlExe||'');const exe=path.join(bin,executable+'.exe');await fs.access(exe).catch(()=>{throw Error(executable+'.exe introuvable. Configure Laragon ou le chemin MySQL.');});
 const args=['--protocol=TCP','--host=127.0.0.1','--port='+c.mysqlPort,'--user='+config.user,'--default-character-set=utf8mb4',...(executable==='mysqldump'?['--single-transaction','--quick','--routines','--events','--triggers','--hex-blob']:['--binary-mode=1','--local-infile=0']),database];
 return new Promise((resolve,reject)=>{const child=spawn(exe,args,{cwd:bin,windowsHide:true,env:{...process.env,MYSQL_PWD:config.password},stdio:['pipe','pipe','pipe']});let failed=false;const stream=output?createWriteStream(output,{flags:'wx',mode:0o600}):null;const timer=setTimeout(()=>{child.kill();reject(Error('MySQL : délai de 10 minutes dépassé.'));},600000);if(stream){child.stdout.pipe(stream);stream.on('error',()=>{failed=true;child.kill();});}else child.stdout.resume();child.stderr.resume();child.stdin.on('error',()=>{});child.on('error',()=>{clearTimeout(timer);stream?.destroy();reject(Error('Client MySQL indisponible.'));});child.on('close',code=>{clearTimeout(timer);if(code||failed){stream?.destroy();reject(Error('Opération MySQL refusée ou échouée. Vérifie les droits et le format SQL.'));}else if(stream&&!stream.writableFinished)stream.once('finish',resolve);else resolve();});child.stdin.end(input||'');});}
 async function dump(database){await fs.mkdir(backups,{recursive:true});const name=database+'-'+Date.now()+'-'+randomUUID().slice(0,8)+'.sql',target=path.join(backups,name);try{await client('mysqldump',database,null,target);}catch(e){await fs.rm(target,{force:true});throw e;}return name;}
 return {
  configured:()=>({user:config.user,passwordSaved:!!config.password}),
  async configure(input){if(typeof input.user!=='string'||!input.user.trim()||input.user.length>100||typeof input.password!=='string'||input.password.length>4096)throw Error('Identifiants invalides.');const next={user:input.user.trim(),password:input.password};await fs.writeFile(file+'.tmp',await seal(JSON.stringify(next)),{mode:0o600});await fs.rename(file+'.tmp',file);config=next;},
  async status(){let conn;try{conn=await connection();const [databases]=await conn.query('SELECT schema_name AS name FROM information_schema.schemata');const [sizes]=await conn.query('SELECT table_schema AS name, COUNT(*) AS tables, COALESCE(SUM(data_length+index_length),0) AS bytes FROM information_schema.tables GROUP BY table_schema');const [processes]=await conn.query('SELECT ID,USER,HOST,DB,COMMAND,TIME,STATE FROM information_schema.PROCESSLIST');return {...this.configured(),databases:databases.filter(d=>!['mysql','sys','performance_schema','information_schema'].includes(d.name)).map(d=>({...d,...sizes.find(s=>s.name===d.name)})),processes};}catch{throw Error('Connexion MySQL impossible. Démarre MySQL et vérifie le compte configuré.');}finally{await conn?.end();}},
  async backups(){await fs.mkdir(backups,{recursive:true});return (await fs.readdir(backups)).filter(n=>/^[\w$-]+\.sql$/.test(n)).sort().reverse();},
  async download(name){if(typeof name!=='string'||!/^[\w$-]+\.sql$/.test(name))throw Error('Sauvegarde invalide.');const target=await fs.realpath(path.join(backups,name));if(path.dirname(target)!==await fs.realpath(backups))throw Error('Chemin invalide.');return target;},
  export(database){databaseName(database);return jobs.create('Export MySQL · '+database,async log=>{const name=await dump(database);log('Sauvegarde disponible : '+name+'\n');},'mysql-admin');},
  import(database,sql,confirm){databaseName(database);if(confirm!==database)throw Error('Recopie le nom de la base pour confirmer le remplacement.');if(typeof sql!=='string'||!sql.trim()||Buffer.byteLength(sql)>20*1024*1024)throw Error('Fichier SQL vide ou supérieur à 20 Mo.');return jobs.create('Import MySQL · '+database,async log=>{log('Sauvegarde de la base avant import…\n');const name=await dump(database);log('Sauvegarde : '+name+'\nImport en cours…\n');await client('mysql',database,sql);log('Import terminé.\n');},'mysql-admin');}
 };
}
