const {app,BrowserWindow,ipcMain,screen}=require('electron');const fs=require('node:fs/promises'),path=require('node:path'),net=require('node:net'),{pathToFileURL}=require('node:url');
const project=path.resolve(__dirname,'..'),packaged=!!process.env.PANEL_SMOKE_PACKAGED,root=packaged?path.join(project,'release','win-unpacked','resources','app.asar'):project;
const output=path.join(project,'.local','install-smoke'),profile=path.join(output,'profile-'+Date.now());app.setPath('userData',profile);let backend,server,window,remote;
const wait=async fn=>{const end=Date.now()+40000;while(!await fn()){if(Date.now()>end)throw Error('UI check timed out');await new Promise(r=>setTimeout(r,100));}};
app.whenReady().then(async()=>{
 await fs.mkdir(output,{recursive:true});const {createApp}=await import(pathToFileURL(path.join(root,'server','index.js')));const {createRemoteDesktop}=await import(pathToFileURL(path.join(root,'desktop','remote-desktop.js')));
 backend=await createApp({requireAuth:false,port:4326,desktop:true,dataDir:profile});server=backend.app.listen(4326,'127.0.0.1');
 window=new BrowserWindow({show:false,x:-20000,y:0,width:1480,height:1000,skipTaskbar:true,focusable:false,webPreferences:{preload:path.join(root,'desktop','preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});window.showInactive();
 remote=await createRemoteDesktop({directory:profile,window,helper:packaged?path.join(project,'release','win-unpacked','resources','rdp-host.exe'):path.join(root,'desktop','rdp-host.exe'),scale:()=>screen.getDisplayMatching(window.getBounds()).scaleFactor});
 for(const action of ['status','save','remove','connect','disconnect','focus','fullscreen'])ipcMain.handle('remote:'+action,(_e,...args)=>remote[action](...args));ipcMain.on('remote:layout',(_e,data)=>remote.layout(data));
 await window.loadURL('http://127.0.0.1:4326');await wait(()=>window.webContents.executeJavaScript("!!document.querySelector('.first-run form')"));await new Promise(r=>setTimeout(r,300));await fs.writeFile(path.join(output,'onboarding.png'),(await window.webContents.capturePage()).toPNG());
 if(backend.settings.get().socialAccounts.length)throw Error('Personal accounts in clean profile');await window.webContents.executeJavaScript("document.querySelector('.first-run form').requestSubmit()");await wait(()=>backend.settings.get().setupComplete);await wait(()=>window.webContents.executeJavaScript("!document.querySelector('.first-run')"));
 const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
 const saved=await remote.save({name:'Test local isolé',host:'127.0.0.1',port,username:'test-only'});await window.webContents.executeJavaScript("Array.from(document.querySelectorAll('nav button')).find(b=>b.textContent==='Bureau distant').click()");await wait(()=>window.webContents.executeJavaScript("!!document.querySelector('.remote-config')"));await new Promise(r=>setTimeout(r,300));await fs.writeFile(path.join(output,'remote.png'),(await window.webContents.capturePage()).toPNG());
 await remote.connect(saved.profiles[0].id,'test-only-password');await wait(()=>['disconnected','error'].includes(remote.status().phase));if(remote.status().phase==='error')throw Error(remote.status().message);
 const data=await fs.readFile(path.join(profile,'rdp-profiles.json'),'utf8');if(data.includes('password'))throw Error('Password persisted');remote.disconnect();backend.close();await backend.workspace.flush();server.close();await fs.writeFile(path.join(output,'result.json'),JSON.stringify({ok:true,packaged,freshOnboarding:true,noPersonalAccounts:true,rdpNativeInitialized:true,loopbackFailureHandled:true,passwordNotSaved:true}));app.exit(0);
}).catch(async e=>{remote?.disconnect();backend?.close();await fs.mkdir(output,{recursive:true});await fs.writeFile(path.join(output,'result.json'),JSON.stringify({ok:false,error:e.stack}));app.exit(1);});

