import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Globe2, Triangle, ArrowUpRight, RefreshCw, Plus, Pencil, Trash2, ShieldCheck, KeyRound, X, LoaderCircle, Check, Search, Clock3, RotateCcw, Terminal, GitBranch, AlertCircle, Server } from 'lucide-react';
import { api } from './api';

function Dialog({ title, close, children }) {
  const ref = useRef();
  useEffect(() => { ref.current.showModal(); }, []);
  return <dialog className="modal cloud-dialog" ref={ref} onCancel={event=>{event.preventDefault();close();}}><header><h2>{title}</h2><button className="icon-button" aria-label="Fermer" onClick={close}><X size={18} /></button></header><div className="modal-body">{children}</div></dialog>;
}
function Loading() { return <div className="loading-state"><LoaderCircle size={22} className="spin" /> Chargement…</div>; }
function ErrorLine({ children }) { return children ? <p className="inline-error" role="alert"><AlertCircle size={15} /> {children}</p> : null; }
function State({ value }) { return <span className={`deploy-state ${value?.toLowerCase()}`}><i />{({READY:'En ligne',ERROR:'Échec',BUILDING:'Construction',QUEUED:'En attente',INITIALIZING:'Initialisation',CANCELED:'Annulé'})[value] || value || '—'}</span>; }
function Connection({ service, configured, settings, onSettings }) {
  const [editing,setEditing] = useState(!configured), [token,setToken] = useState(''), [team,setTeam] = useState(settings.vercelTeamId || ''), [busy,setBusy] = useState(false), [error,setError] = useState('');
  const hostinger = service === 'Hostinger';
  async function save(e) { e.preventDefault(); setBusy(true); setError(''); try { const result = await api('/settings', { [hostinger ? 'hostingerToken' : 'vercelToken']: token, ...(!hostinger ? { vercelTeamId: team } : {}) }); onSettings(result); setToken(''); setEditing(false); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <section className={`connection-card ${configured ? 'configured' : ''}`}><div className="connection-identity"><div className={`provider-icon ${hostinger ? 'hostinger' : 'vercel'}`}>{hostinger ? <Globe2 size={25} /> : <Triangle size={25} fill="currentColor" />}</div><div><h2>{configured ? `${service} est configuré` : `Connecter ${service}`}</h2><p>{configured ? 'La clé est conservée dans le coffre Windows.' : hostinger ? 'Retrouve tes domaines et modifie tes DNS depuis ton espace.' : 'Tes projets, tes déploiements et leurs journaux réunis ici.'}</p></div>{configured && <button className="button secondary small" onClick={() => setEditing(!editing)}><KeyRound size={14} />{editing ? 'Fermer' : 'Connexion'}</button>}</div>
    {editing && <form onSubmit={save} className="connection-form"><label>Clé API {service}<input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} required={!configured} placeholder={configured ? 'Laisser vide pour conserver la clé' : 'Colle ta clé API'} /></label>{!hostinger && <label>Team ID <span className="muted">facultatif</span><input value={team} onChange={e=>setTeam(e.target.value)} placeholder="team_… ou vide pour ton compte" /></label>}<div><a className="text-link" target="_blank" rel="noreferrer" href={hostinger ? 'https://hpanel.hostinger.com/profile/api' : 'https://vercel.com/account/settings/tokens'}>Créer ma clé chez {service}<ArrowUpRight size={14} /></a><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <Check size={16} />}Enregistrer</button></div><ErrorLine>{error}</ErrorLine></form>}
  </section>;
}

export function DomainsPage({ settings, onSettings, notice }) {
  const [domains,setDomains] = useState([]), [domain,setDomain] = useState(''), [manual,setManual] = useState(''), [zone,setZone] = useState(null), [error,setError] = useState(''), [busy,setBusy] = useState(false), [query,setQuery] = useState(''), [edit,setEdit] = useState(null), [plan,setPlan] = useState(null), [confirm,setConfirm] = useState('');
  const [history,setHistory]=useState(null);
  const generation = useRef(0);
  const refresh = useCallback(async () => { setBusy(true); setError(''); try { const data = await api('/hostinger'); setDomains(data.domains); setDomain(current => current || data.domains[0]?.domain || ''); } catch (e) { setError(e.message); } finally { setBusy(false); } }, []);
  useEffect(()=>{ if(settings.hostingerConfigured) refresh(); },[settings,refresh]);
  const readZone = useCallback(async selected => { const current = ++generation.current; setBusy(true); setError(''); setZone(null); try { const data = await api(`/hostinger/${encodeURIComponent(selected)}/dns`); if(current===generation.current) setZone(data); } catch(e) { if(current===generation.current) setError(e.message); } finally { if(current===generation.current) setBusy(false); } },[]);
  useEffect(()=>{ setHistory(null);if(domain && settings.hostingerConfigured) readZone(domain); return ()=>{ generation.current++; }; },[domain,settings,readZone]);
  async function prepare(action) { setBusy(true); setError(''); try { const record = { name:edit.name,type:edit.type,ttl:Number(edit.ttl),records:edit.content.split('\n').filter(v=>v.trim()).map(content=>({content})) }; setPlan(await api(`/hostinger/${encodeURIComponent(domain)}/plan`,{action,record,fingerprint:zone.fingerprint})); setConfirm(''); } catch(e){setError(e.message);} finally{setBusy(false);} }
  async function apply() { setBusy(true); setError(''); try { await api('/hostinger/apply',{planId:plan.planId,confirm}); setPlan(null);setEdit(null);notice('Modification DNS envoyée à Hostinger. La propagation peut prendre du temps.');await readZone(domain); } catch(e){setError(e.message);setPlan(null);} finally{setBusy(false);} }
  return <div className="cloud-page"><Connection service="Hostinger" configured={settings.hostingerConfigured} settings={settings} onSettings={onSettings} />
    {settings.hostingerConfigured && <><div className="domain-layout"><aside className="domain-picker"><div className="section-heading"><h3>Mes domaines</h3><button className="icon-button" aria-label="Actualiser les domaines" disabled={busy} onClick={refresh}><RefreshCw size={15}/></button></div>{domains.map(d=><button className={domain===d.domain?'selected':''} key={d.domain} onClick={()=>setDomain(d.domain)}><Globe2 size={19}/><span><strong>{d.domain}</strong><small>{d.expiresAt ? `Expire le ${new Date(d.expiresAt).toLocaleDateString('fr-FR')}` : d.status || 'Domaine'}</small></span></button>)}<form onSubmit={e=>{e.preventDefault();setDomain(manual.trim());}}><label>Ouvrir une zone DNS<input aria-label="Nom de domaine" value={manual} onChange={e=>setManual(e.target.value)} placeholder="mondomaine.fr" required/></label><button className="button secondary small" disabled={busy}>Ouvrir<ArrowUpRight size={13}/></button></form></aside>
    <section className="card dns-card"><div className="card-heading"><div><span className="eyebrow">ZONE DNS</span><h2>{domain || 'Sélectionne un domaine'}</h2></div><button className="button primary small" disabled={!zone||busy} onClick={()=>{setEdit({name:'@',type:'A',ttl:3600,content:'',fresh:true});setError('');}}><Plus size={15}/>Ajouter</button></div>{domain && <div className="dns-toolbar"><div className="mini-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un nom, type ou contenu…" aria-label="Rechercher dans les DNS"/></div><button className="icon-button" title="Actualiser la zone" disabled={busy} onClick={()=>readZone(domain)}><RefreshCw size={16}/></button></div>}
      {busy&&!zone ? <Loading/> : !zone ? <div className="cloud-empty"><Globe2 size={36}/><h3>Choisis ton domaine.</h3><p>Ses enregistrements DNS apparaîtront ici.</p></div> : <div className="dns-table-wrap"><table className="dns-table"><thead><tr><th>Type</th><th>Nom</th><th>Valeurs</th><th>TTL</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{zone.records.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map((r,i)=><tr key={`${r.type}:${r.name}:${i}`}><td><span className="dns-type">{r.type}</span></td><td><code>{r.name}</code></td><td>{r.records?.map((v,j)=><div key={j}><code>{v.content}</code>{v.is_disabled&&<small> · Désactivé</small>}</div>)}</td><td>{r.ttl}s</td><td><button className="icon-button" aria-label={`Modifier ${r.type} ${r.name}`} disabled={busy||!['A','AAAA','CNAME','TXT','MX','SRV','CAA','NS'].includes(r.type)} onClick={()=>{setEdit({...r,content:r.records.map(v=>v.content).join('\n'),fresh:false});setError('');}}><Pencil size={15}/></button></td></tr>)}</tbody></table>{!zone.records.length&&<p className="cloud-empty">La zone ne contient aucun enregistrement.</p>}</div>}
      <div className="dns-note"><button className="button secondary small" disabled={!domain||busy} onClick={async()=>{try{setHistory(await api('/hostinger/'+encodeURIComponent(domain)+'/history'));}catch(e){setError(e.message);}}}>Historique & restauration</button><ShieldCheck size={16}/><span>Un aperçu avant/après précède chaque modification. Une copie locale de la zone est conservée avant envoi.</span></div></section></div></>}
    {history&&<section className="card workspace-panel"><div className="workspace-actions"><h2>Versions précédentes de {domain}</h2><button className="button secondary" onClick={()=>setHistory(null)}>Fermer</button></div><p>Choisis un groupe à restaurer. L’aperçu avant/après et la confirmation s’afficheront avant tout envoi.</p>{!history.length&&<p>Aucune sauvegarde DNS pour ce domaine.</p>}{history.map(h=><details key={h.id}><summary>{new Date(Number(h.id.match(/-(\d+)\.json$/)?.[1])).toLocaleString('fr-FR')}</summary>{h.records.map((r,i)=><div className="workspace-row" key={i}><div><strong>{r.type} {r.name}</strong><pre>{r.records?.map(v=>v.content).join('\n')}</pre></div><button className="button secondary small" disabled={busy||!zone||r.records?.some(v=>v.is_disabled)||!['A','AAAA','CNAME','TXT','MX','SRV','CAA','NS'].includes(r.type)} onClick={()=>{setEdit({...r,content:r.records.map(v=>v.content).join('\n'),fresh:false});setPlan(null);setConfirm('');}}>Préparer la restauration</button></div>)}</details>)}</section>}{!edit&&<ErrorLine>{error}</ErrorLine>}
    {edit&&<Dialog title={plan?'Vérifier la modification DNS':edit.fresh?'Ajouter un enregistrement':'Modifier le groupe DNS'} close={()=>{if(!busy){setEdit(null);setPlan(null);setError('');}}}>
      {plan ? <><p>La modification s’appliquera à <strong>{plan.domain}</strong>. Tous les enregistrements du groupe <strong>{(plan.after||plan.before).type} {(plan.after||plan.before).name}</strong> sont affichés ci-dessous.</p><div className="dns-diff"><div><span>AVANT</span><pre>{plan.before?JSON.stringify(plan.before,null,2):'Aucun enregistrement'}</pre></div><div><span>APRÈS</span><pre>{plan.after?JSON.stringify(plan.after,null,2):'Groupe supprimé'}</pre></div></div><label>Recopie {plan.domain} pour appliquer<input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/></label><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setPlan(null)}>Modifier</button><button className="button primary" disabled={busy||confirm!==plan.domain} onClick={apply}>{busy?'Application…':'Appliquer les DNS'}</button></div></>
        : <form onSubmit={e=>{e.preventDefault();prepare('save');}}><div className="form-columns"><label>Type<select disabled={!edit.fresh} value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value})}>{['A','AAAA','CNAME','TXT','MX','SRV','CAA','NS'].map(v=><option key={v}>{v}</option>)}</select></label><label>Nom<input required disabled={!edit.fresh} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label></div><label>Valeurs · une par ligne<textarea required rows={5} value={edit.content} onChange={e=>setEdit({...edit,content:e.target.value})} placeholder={edit.type==='A'?'203.0.113.10':'Contenu de l’enregistrement'}/></label><label>TTL en secondes<input type="number" min="60" max="604800" required value={edit.ttl} onChange={e=>setEdit({...edit,ttl:e.target.value})}/></label><div className="modal-actions">{!edit.fresh&&<button type="button" className="button danger" disabled={busy} onClick={()=>prepare('delete')}><Trash2 size={15}/>Supprimer ce groupe</button>}<button className="button primary" disabled={busy}>{busy?'Vérification…':'Vérifier les changements'}<ArrowUpRight size={15}/></button></div></form>}
      <ErrorLine>{error}</ErrorLine></Dialog>}
  </div>;
}

export function VercelPage({ settings, onSettings, notice }) {
  const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState('all'),[logs,setLogs]=useState(null),[plan,setPlan]=useState(null),[confirm,setConfirm]=useState('');
  const refresh=useCallback(async()=>{setBusy(true);setError('');try{setData(await api('/vercel'));}catch(e){setError(e.message);}finally{setBusy(false);}},[]);
  useEffect(()=>{if(settings.vercelConfigured){refresh();const timer=setInterval(()=>{if(!document.hidden)refresh();},30000);return()=>clearInterval(timer);}},[settings,refresh]);
  async function events(item){setBusy(true);setError('');try{setLogs({name:item.name,...await api(`/vercel/${item.id}/events`)});}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function prepare(item){setBusy(true);setError('');try{setPlan(await api(`/vercel/${item.id}/plan`,{}));setConfirm('');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function apply(){setBusy(true);setError('');try{await api('/vercel/redeploy',{planId:plan.planId,confirm});setPlan(null);notice('Le redéploiement Vercel est lancé.');await refresh();}catch(e){setError(e.message);setPlan(null);}finally{setBusy(false);}}
  const items=data?.deployments?.filter(d=>selected==='all'||d.projectId===selected)||[];
  return <div className="cloud-page"><Connection service="Vercel" configured={settings.vercelConfigured} settings={settings} onSettings={onSettings}/><ErrorLine>{error}</ErrorLine>
    {settings.vercelConfigured && (busy&&!data?<Loading/>:<><div className="vercel-summary"><div><span>Projets</span><strong>{data?.projects.length??'—'}</strong></div><div><span>Prêts parmi les derniers déploiements</span><strong>{data?.deployments.filter(d=>d.state==='READY').length??'—'}</strong></div><div><span>Builds en cours</span><strong>{data?.deployments.filter(d=>['BUILDING','QUEUED','INITIALIZING'].includes(d.state)).length??'—'}</strong></div></div><div className="section-heading"><h2>Mes projets</h2><button className="button secondary small" disabled={busy} onClick={refresh}><RefreshCw size={14}/>Actualiser</button></div><div className="vercel-projects">{data?.projects.map(p=><button key={p.id} className={`vercel-project ${selected===p.id?'selected':''}`} onClick={()=>setSelected(selected===p.id?'all':p.id)}><Triangle size={24} fill="currentColor"/><h3>{p.name}</h3><p>{p.production||p.framework||'Projet Vercel'}</p><footer><span><GitBranch size={12}/>{p.git||'Dépôt non lié'}</span><ArrowUpRight size={16}/></footer></button>)}</div>
    <section className="card deployments"><div className="card-heading"><h2>Derniers déploiements</h2>{selected!=='all'&&<button className="text-link" onClick={()=>setSelected('all')}>Tous les projets<X size={14}/></button>}</div>{!items.length?<div className="cloud-empty"><Triangle size={32}/><h3>Aucun déploiement à afficher.</h3><p>Les déploiements de ton compte apparaîtront ici.</p></div>:items.map(item=><article className="deployment" key={item.id}><span className="deployment-mark"><Triangle size={17}/></span><div className="deployment-info"><h3>{item.name}<span>{item.target}</span></h3><p>{item.commit||item.url||item.id}</p><small><GitBranch size={12}/>{item.branch||'—'}<span>·</span><Clock3 size={12}/>{new Date(item.createdAt).toLocaleString('fr-FR')}</small></div><State value={item.state}/><div className="deployment-actions"><button className="icon-button" aria-label={`Journaux ${item.name}`} title="Journaux du build" disabled={busy} onClick={()=>events(item)}><Terminal size={17}/></button><button className="icon-button" aria-label={`Redéployer ${item.name}`} title="Redéployer" disabled={busy||!['READY','ERROR','CANCELED'].includes(item.state)} onClick={()=>prepare(item)}><RotateCcw size={17}/></button>{item.url&&<a className="icon-button" href={`https://${item.url}`} target="_blank" rel="noreferrer" title="Voir le site"><ArrowUpRight size={17}/></a>}</div></article>)}<footer className="dns-note"><ShieldCheck size={15}/>{data?.moreDeployments?'Les 40 derniers déploiements du compte sont affichés.':'Déploiements du compte sélectionné.'}<a className="text-link" href="https://vercel.com/dashboard" target="_blank" rel="noreferrer">Ouvrir Vercel<ArrowUpRight size={13}/></a></footer></section></>)}
    {logs&&<Dialog title={`Journaux · ${logs.name}`} close={()=>setLogs(null)}><pre className="log-output">{logs.output||'Aucune sortie de build disponible.'}</pre></Dialog>}
    {plan&&<Dialog title="Redéployer sur Vercel" close={()=>{if(!busy)setPlan(null);}}><p>Relancer le build de <strong>{plan.name}</strong> à partir du déploiement sélectionné, vers <strong>{plan.target}</strong>. {plan.target==='production'&&'Les domaines de production seront mis à jour si le build réussit.'}</p><label>Recopie {plan.name} pour confirmer<input value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setPlan(null)}>Annuler</button><button className="button primary" disabled={busy||confirm!==plan.name} onClick={apply}>{busy?'Envoi…':'Redéployer'}</button></div></Dialog>}
  </div>;
}
