import React,{useEffect,useRef,useState} from 'react';
import {api} from './api.js';
export default function CreatorPage({kind,desktop,suspended=false,notice}){
 const isImage=kind==='chatgpt',id='creator-'+kind,slot=useRef(null);
 const [phase,setPhase]=useState('loading'),[error,setError]=useState('');
 const [prompt,setPrompt]=useState(()=>{try{return localStorage.getItem('creator-draft-'+kind)||'';}catch{return '';}});
 const bridge=window.socialSurface;
 useEffect(()=>{if(!desktop||!bridge)return;let active=true;const accept=s=>{if(active&&s.accountId===id)setPhase(s.panels[0]?.phase||'loading');};const off=bridge.onStatus(accept);bridge.mount(id).then(accept).catch(e=>setError(e.message));return()=>{active=false;off();bridge.close();};},[id,desktop]);
 useEffect(()=>{if(!desktop||!bridge)return;let frame;const layout=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const r=slot.current?.getBoundingClientRect();bridge.layout({accountId:id,visible:!suspended&&!document.hidden,panels:{create:r?{x:r.x,y:r.y,width:r.width,height:r.height}:null},zoom:1});});};const ro=new ResizeObserver(layout);if(slot.current)ro.observe(slot.current);window.addEventListener('scroll',layout,true);window.addEventListener('resize',layout);document.addEventListener('visibilitychange',layout);layout();return()=>{cancelAnimationFrame(frame);ro.disconnect();window.removeEventListener('scroll',layout,true);window.removeEventListener('resize',layout);document.removeEventListener('visibilitychange',layout);};},[id,desktop,suspended,phase]);
 async function open(external=false){try{const result=await api('/social/'+id+'/open',{target:'create',external});if(result.url)window.open(result.url,'_blank','noopener,noreferrer');}catch(e){notice(e.message,'error');}}
 return <section className="creator-space"><div className="creator-intro"><span className="eyebrow">TON STUDIO CRÉATIF</span><h2>{isImage?'De l’idée à l’image.':'Trouve ta prochaine mélodie.'}</h2><p>{isImage?'Décris ton image dans ChatGPT ou ouvre son espace Images. Tu utilises les possibilités de ton compte ChatGPT ; aucun crédit API n’est inclus ou consommé par ce dashboard.':'Crée dans Suno : description, style, paroles et mode instrumental selon les options de ton compte. Les générations et crédits sont gérés par Suno.'}</p><p>Connecte-toi une première fois. Si le site refuse la connexion intégrée, utilise ton navigateur. Tu confirmes chaque génération dans le service officiel.</p><label>{isImage?'Préparer une description':'Préparer un style ou des paroles'}<textarea rows={3} maxLength={12000} value={prompt} onChange={e=>{setPrompt(e.target.value);try{localStorage.setItem('creator-draft-'+kind,e.target.value);}catch{}}} placeholder={isImage?'Sujet, ambiance, lumière, cadrage…':'Genre, instruments, humeur, paroles…'}/></label><div className="social-live-tools"><button className="button primary" onClick={async()=>{try{await navigator.clipboard.writeText(prompt);notice('Brouillon copié : colle-le dans le service.');}catch{notice('Copie indisponible : sélectionne le texte du brouillon.','error');}}} disabled={!prompt}>Copier le brouillon</button><button className="button secondary" onClick={()=>open(true)}>Ouvrir dans le navigateur</button><button className="button secondary" onClick={()=>open()}>Fenêtre séparée</button><button className="button secondary" disabled={!bridge} onClick={()=>bridge.refresh().catch(e=>setError(e.message))}>Actualiser</button></div></div>{error&&<p role="alert">{error}</p>}<div className="social-native-slot creator-slot" ref={slot}><div className="social-native-placeholder"><h3>{!desktop?'Disponible dans l’application Windows':phase==='error'?'Service indisponible dans cette vue':'Espace officiel '+(isImage?'ChatGPT':'Suno')}</h3><p>Utilise le navigateur si la connexion ou l’affichage n’aboutit pas.</p><button className="button secondary" onClick={()=>open(true)}>Ouvrir le service</button></div></div></section>;
}
