import React, { useCallback, useEffect, useRef, useState } from 'react';
import { MessageCircle, Bot, Users, Shield, RefreshCw, ArrowUpRight, LoaderCircle, Download, X, Search, KeyRound, Plus, AlertCircle } from 'lucide-react';
import { api } from './api';

const ACTIONS = { kick:'Expulser',ban:'Bannir',unban:'Débannir',timeout:'Exclure temporairement',clear_timeout:'Retirer l’exclusion temporaire',nickname:'Changer le pseudo',role_add:'Ajouter un rôle',role_remove:'Retirer un rôle',mute:'Couper le micro en vocal',unmute:'Rétablir le micro en vocal',deafen:'Couper l’écoute en vocal',undeafen:'Rétablir l’écoute en vocal',disconnect_voice:'Déconnecter du vocal' };
const bridge = window.socialSurface;
const errorLine = message => message && <p className="inline-error" role="alert"><AlertCircle size={15}/>{message}</p>;
const stamp = value => value ? new Date(value).toLocaleString('fr-FR') : '—';

function PersonalDiscord({ suspended, desktop }) {
  const slot=useRef(), [phase,setPhase]=useState('loading'), [error,setError]=useState('');
  const native=desktop&&!!bridge;
  useEffect(()=>{
    if(!native)return;
    let active=true;
    const update=state=>{if(active&&state.accountId==='discord-personal')setPhase(state.panels[0]?.phase||'loading');};
    const unsubscribe=bridge.onStatus(update);
    bridge.mount('discord-personal').then(update).catch(e=>{if(active)setError(e.message);});
    return()=>{active=false;unsubscribe();bridge.close();};
  },[native]);
  useEffect(()=>{
    if(!native)return;
    let frame;
    const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const rect=slot.current?.getBoundingClientRect();if(rect)bridge.layout({accountId:'discord-personal',visible:!suspended&&!document.hidden,panels:{client:{x:rect.x,y:rect.y,width:rect.width,height:rect.height}}});});};
    const observer=new ResizeObserver(update);if(slot.current)observer.observe(slot.current);
    window.addEventListener('resize',update);window.addEventListener('scroll',update,true);document.addEventListener('visibilitychange',update);update();
    return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true);document.removeEventListener('visibilitychange',update);};
  },[native,suspended,phase]);
  return <><div className="discord-personal-note"><MessageCircle size={23}/><div><h2>Tes conversations et tes serveurs</h2><p>Connecte-toi à Discord ci-dessous. Tes DM récents apparaissent à gauche, et tes serveurs dans la barre latérale. Pour quitter un serveur : clic droit sur son icône → Quitter le serveur, puis confirme dans Discord.</p></div><button className="button secondary small" disabled={!native} onClick={()=>bridge.refresh('client').catch(e=>setError(e.message))}><RefreshCw size={15}/>Actualiser</button></div>{errorLine(error)}<section className="social-live-panel discord-client"><header><h3><MessageCircle size={17}/>Mon Discord</h3><span>{phase==='login'?'Connexion nécessaire':phase==='ready'?'Interface officielle':'Session personnelle'}</span><a className="text-link" href="https://discord.com/channels/@me" target="_blank" rel="noreferrer">Ouvrir dans le navigateur<ArrowUpRight size={14}/></a></header><div ref={slot} className="social-native-slot"><div className="social-native-placeholder">{phase==='error'?<AlertCircle size={30}/>:<MessageCircle size={36}/>}<h3>{!native?'Disponible dans l’application Windows':phase==='error'?'Discord ne répond pas.':'Ouverture de Discord…'}</h3><p>{!native?'Ouvre LeStitcheur Control depuis ton raccourci bureau.':'La session reste sur ce PC. Aucun jeton de compte personnel n’est demandé.'}</p></div></div></section></>;
}
function ActionDialog({ target, guild, botId, kind, onClose, onDone }) {
  const dialog=useRef();
  const choices=(guild.actions||[]).filter(action=>kind==='bans'?action==='unban':action!=='unban');
  const [action,setAction]=useState(choices[0]||''),[reason,setReason]=useState(''),[minutes,setMinutes]=useState(60),[nick,setNick]=useState(target.nick||''),[roleId,setRoleId]=useState(''),[plan,setPlan]=useState(null),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{dialog.current.showModal();},[]);
  const close=()=>{if(!busy)onClose();};
  async function prepare(e){e.preventDefault();setBusy(true);setError('');try{setPlan(await api(`/discord/bots/${botId}/guilds/${guild.id}/plan`,{action,userId:target.id,reason,minutes:Number(minutes),nick,roleId}));setConfirm('');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function apply(){setBusy(true);setError('');try{await api('/discord/apply',{planId:plan.planId,confirm});onDone();}catch(e){setError(e.message);setPlan(null);}finally{setBusy(false);}}
  return <dialog ref={dialog} className="modal cloud-dialog" onCancel={e=>{e.preventDefault();close();}}><header><h2>{plan?'Confirmer l’action Discord':'Gérer un membre'}</h2><button className="icon-button" aria-label="Fermer" disabled={busy} onClick={close}><X size={18}/></button></header><div className="modal-body"><div className="discord-target"><strong>{target.name} · @{target.username}</strong><code>{target.id}</code><span>{guild.name}</span></div>{plan?<><div className="discord-confirm-summary"><h3>{plan.label}</h3><p>Bot : <strong>{plan.botName}</strong> · Serveur : <strong>{plan.guildName}</strong></p><p>Raison : {plan.reason}</p>{plan.action==='timeout'&&<p>Durée : {plan.minutes} minutes</p>}{plan.action==='nickname'&&<p>Nouveau pseudo : {plan.nick||'Pseudo du compte'}</p>}{plan.roleName&&<p>Rôle : {plan.roleName}</p>}{plan.action==='ban'&&<p>Le membre sera banni. Son historique de messages est conservé.</p>}</div><label>Recopie l’identifiant {target.id} pour confirmer<input autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setPlan(null)}>Modifier</button><button className="button danger" disabled={busy||confirm!==target.id} onClick={apply}>{busy?'Application…':'Appliquer l’action'}</button></div></>:<form onSubmit={prepare}><label>Action<select value={action} onChange={e=>setAction(e.target.value)}>{choices.map(value=><option key={value} value={value}>{ACTIONS[value]}</option>)}</select></label>{action==='timeout'&&<label>Durée en minutes<input type="number" required min="1" max="40320" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label>}{action==='nickname'&&<label>Nouveau pseudo · vide pour retirer le pseudo<input maxLength={32} value={nick} onChange={e=>setNick(e.target.value)}/></label>}{action.startsWith('role_')&&<label>Rôle<select required value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">Choisir un rôle…</option>{guild.roles.filter(r=>r.manageable&&(action==='role_remove'?target.roles?.includes(r.id):!target.roles?.includes(r.id))).map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label>}<label>Raison · enregistrée dans le journal d’audit Discord<textarea required maxLength={200} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="field-help">Les permissions et la hiérarchie du bot sont revérifiées avant l’envoi. Les actions vocales nécessitent que le membre soit connecté à un salon vocal.</p><div className="modal-actions"><button className="button primary" disabled={busy||!action}>{busy?'Vérification…':'Vérifier l’action'}</button></div></form>}{errorLine(error)}</div></dialog>;
}
function BotAdmin({ notice }) {
  const [bots,setBots]=useState([]),[botId,setBotId]=useState(''),[guilds,setGuilds]=useState([]),[guildNext,setGuildNext]=useState(null),[guildId,setGuildId]=useState(''),[guild,setGuild]=useState(null),[kind,setKind]=useState('members'),[items,setItems]=useState([]),[next,setNext]=useState(null),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[listError,setListError]=useState(''),[token,setToken]=useState(''),[name,setName]=useState(''),[connecting,setConnecting]=useState(false),[showConnect,setShowConnect]=useState(false),[target,setTarget]=useState(null),[revision,setRevision]=useState(0);
  const scope=useRef('');scope.current=`${botId}:${guildId}:${kind}`;
  const guildScope=useRef('');guildScope.current=botId;
  const loadBots=useCallback(async()=>{try{const data=await api('/discord/bots');setBots(data.bots);setBotId(current=>data.bots.some(b=>b.id===current)?current:data.bots[0]?.id||'');}catch(e){setError(e.message);}},[]);
  useEffect(()=>{loadBots();},[loadBots]);
  useEffect(()=>{let active=true;setGuilds([]);setGuildId('');setGuild(null);setItems([]);setGuildNext(null);setError('');if(botId){setBusy(true);api(`/discord/bots/${botId}/guilds`).then(data=>{if(active){setGuilds(data.items);setGuildNext(data.next);setGuildId(data.items[0]?.id||'');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});}return()=>{active=false;};},[botId]);
  useEffect(()=>{let active=true;setGuild(null);setError('');if(botId&&guildId)api(`/discord/bots/${botId}/guilds/${guildId}`).then(data=>{if(active)setGuild(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[botId,guildId,revision]);
  useEffect(()=>{let active=true;setItems([]);setNext(null);setQuery('');setListError('');if(botId&&guildId){setBusy(true);api(`/discord/bots/${botId}/guilds/${guildId}/${kind}`).then(data=>{if(active){setItems(data.items);setNext(data.next);}}).catch(e=>{if(active)setListError(e.message);}).finally(()=>{if(active)setBusy(false);});}return()=>{active=false;};},[botId,guildId,kind,revision]);
  async function connect(e){e.preventDefault();setConnecting(true);setError('');try{const result=await api('/discord/bots',{token,name});setToken('');setName('');await loadBots();setBotId(result.id);setShowConnect(false);notice('Bot connecté. Son jeton est chiffré sur ce PC.');}catch(e){setError(e.message);}finally{setConnecting(false);}}
  async function disconnect(){const selected=bots.find(b=>b.id===botId);if(!window.confirm(`Déconnecter ${selected.name} du dashboard ? Le bot restera sur ses serveurs Discord.`))return;setBusy(true);try{await api(`/discord/bots/${botId}/disconnect`,{});await loadBots();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function moreGuilds(){const captured=botId;setBusy(true);try{const data=await api(`/discord/bots/${botId}/guilds?after=${guildNext}`);if(guildScope.current===captured){setGuilds(current=>[...current,...data.items.filter(item=>!current.some(g=>g.id===item.id))]);setGuildNext(data.next);}}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function more(){const captured=scope.current;setBusy(true);try{const data=await api(`/discord/bots/${botId}/guilds/${guildId}/${kind}?after=${next}`);if(scope.current===captured){setItems(current=>[...current,...data.items.filter(item=>!current.some(m=>m.id===item.id))]);setNext(data.next);}}catch(e){if(scope.current===captured)setListError(e.message);}finally{setBusy(false);}}
  function exportList(){const data={guildId,guildName:guild?.name,kind,exportedAt:new Date().toISOString(),complete:!next,items};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`discord-${guildId}-${kind}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const filtered=items.filter(item=>[item.username,item.name,item.nick,item.id].some(value=>value?.toLowerCase().includes(query.toLowerCase())));
  return <div className="discord-admin cloud-page"><section className="connection-card"><div className="connection-identity"><div className="provider-icon discord"><Bot size={26}/></div><div><h2>Mes bots Discord</h2><p>Connecte les bots que tu gères pour retrouver leurs serveurs.</p></div><button className="button secondary small" onClick={()=>setShowConnect(!showConnect)}><Plus size={15}/>{showConnect?'Fermer':'Connecter un bot'}</button></div>{(showConnect||!bots.length)&&<form className="connection-form" onSubmit={connect}><div className="form-columns"><label>Nom du bot · facultatif<input maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Mon bot de modération"/></label><label>Jeton du bot<input type="password" required autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Bot → Token dans le portail Discord"/></label></div><p className="field-help">Jeton de bot uniquement. Pour lister les membres, active « Server Members Intent » dans la configuration du bot. Les actions nécessitent les permissions correspondantes et un rôle au-dessus des membres ciblés.</p><div><a className="text-link" href="https://discord.com/developers/applications" target="_blank" rel="noreferrer">Portail développeur Discord<ArrowUpRight size={14}/></a><button className="button primary" disabled={connecting}>{connecting?<LoaderCircle size={16} className="spin"/>:<KeyRound size={16}/>}Connecter</button></div></form>}</section>{errorLine(error)}
    {!!bots.length&&<><div className="discord-selectors"><label>Bot<select value={botId} onChange={e=>setBotId(e.target.value)}>{bots.map(bot=><option key={bot.id} value={bot.id}>{bot.name}</option>)}</select></label><label>Serveurs où ce bot est présent<select value={guildId} onChange={e=>setGuildId(e.target.value)} disabled={!guilds.length}><option value="">{busy?'Chargement…':'Choisir un serveur'}</option>{guilds.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button ghost small" disabled={busy} onClick={disconnect}>Déconnecter ce bot</button>{guildNext&&<button className="button secondary small" disabled={busy} onClick={moreGuilds}>Plus de serveurs</button>}</div>{!guildId&&!busy&&<p className="section-note">Aucun serveur chargé pour ce bot. Vérifie qu’il a été invité sur les serveurs voulus.</p>}</>}
    {guild&&<><div className="section-heading"><div><span className="eyebrow">SERVEUR DISCORD</span><h2>{guild.name}</h2></div><button className="button secondary small" disabled={busy} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={15}/>Actualiser</button></div><div className="discord-stats">{[['Membres · estimation',guild.members],['En ligne · estimation',guild.online],['Salons accessibles',guild.channels],['Rôles',guild.roles.length],['Boosts',guild.boosts]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value??'—'}</strong></div>)}</div><p className="field-help">Relevé le {stamp(guild.checkedAt)} · Niveau de boost {guild.boostLevel??'—'}. Aucun historique de messages ou de croissance n’est calculé.</p></>}
    {guildId&&<section className="card discord-members"><div className="card-heading"><div className="filter-row"><button className={kind==='members'?'selected':''} onClick={()=>setKind('members')}><Users size={15}/>Membres</button><button className={kind==='bans'?'selected':''} onClick={()=>setKind('bans')}><Shield size={15}/>Bannis</button></div><button className="button secondary small" disabled={!items.length||busy} onClick={exportList}><Download size={14}/>Exporter les {items.length} chargés</button></div><div className="discord-list-search"><Search size={17}/><input aria-label="Rechercher parmi les membres chargés" placeholder="Rechercher parmi les membres chargés…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{items.length} chargés{next?' · liste partielle':''}</span></div>{errorLine(listError)}<div className="dns-table-wrap"><table className="dns-table"><thead><tr><th>Membre</th><th>{kind==='members'?'Arrivée / exclusion':'Raison du bannissement'}</th><th>Actions</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.nick||item.name}</strong>{item.bot&&<span className="badge">Bot</span>}<small>@{item.username} · {item.id}</small></td><td>{kind==='bans'?item.reason||'Aucune raison fournie':<><span>{stamp(item.joinedAt)}</span>{item.timeoutUntil&&new Date(item.timeoutUntil)>new Date()&&<small>Exclu jusqu’au {stamp(item.timeoutUntil)}</small>}</>}</td><td><button className="button secondary small" disabled={busy||!guild||(kind==='bans'?!guild.actions.includes('unban'):!guild.actions.some(a=>a!=='unban'))} onClick={()=>setTarget(item)}>{kind==='bans'?'Débannir':'Gérer'}</button></td></tr>)}</tbody></table></div>{busy&&<div className="loading-state"><LoaderCircle className="spin" size={20}/>Chargement…</div>}{!busy&&!listError&&!filtered.length&&<div className="cloud-empty">Aucun résultat.</div>}<footer className="discord-list-footer"><span>Les actions sont réalisées par le bot sélectionné.</span>{next&&<button className="button secondary small" disabled={busy} onClick={more}>Charger les membres suivants</button>}</footer></section>}
    {target&&guild&&<ActionDialog key={`${target.id}:${kind}`} target={target} guild={guild} botId={botId} kind={kind} onClose={()=>setTarget(null)} onDone={()=>{setTarget(null);setRevision(v=>v+1);notice('Action Discord effectuée.');}}/>}
  </div>;
}
export default function DiscordPage({ desktop, suspended, notice }) {
  const [tab,setTab]=useState('personal');
  return <div className="discord-page"><div className="discord-page-tabs"><button className={tab==='personal'?'selected':''} onClick={()=>setTab('personal')}><MessageCircle size={18}/>DM & mes serveurs</button><button className={tab==='bots'?'selected':''} onClick={()=>setTab('bots')}><Bot size={18}/>Serveurs de mes bots</button></div>{tab==='personal'?<PersonalDiscord desktop={desktop} suspended={suspended}/>:<BotAdmin notice={notice}/>}</div>;
}
