import React,{useEffect,useRef,useState} from 'react';
import {Github,RefreshCw,Search,ExternalLink,GitBranch,Star,Rocket,Upload,Terminal,Code2} from 'lucide-react';
import {api} from './api';
const tabs={issues:'Issues',pulls:'Pull requests',runs:'Actions',releases:'Releases'};
const safeLink=url=>{try{const parsed=new URL(url);return parsed.protocol==='https:'&&parsed.hostname==='github.com'&&!parsed.username&&!parsed.password?url:'#';}catch{return '#';}};
export default function GithubPage({projects,projectAction}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(null),[details,setDetails]=useState(null),[detailError,setDetailError]=useState(''),[tab,setTab]=useState('issues');
 const request=useRef(0),detailRequest=useRef(0);
 async function load(page=1){const id=++request.current;setLoading(true);setError('');try{const result=await api(`/github?page=${page}`);if(request.current===id)setData(prev=>({...result,repos:page===1?result.repos:[...(prev?.repos||[]),...result.repos].filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i)}));}catch(e){if(request.current===id)setError(e.message);}finally{if(request.current===id)setLoading(false);}}
 useEffect(()=>{load();return()=>{request.current++;};},[]);
 useEffect(()=>{const id=++detailRequest.current;setDetails(null);setDetailError('');if(selected)api(`/github/${selected.fullName.split('/').map(encodeURIComponent).join('/')}`).then(result=>{if(detailRequest.current===id)setDetails(result);}).catch(e=>{if(detailRequest.current===id)setDetailError(e.message);});return()=>{detailRequest.current++;};},[selected]);
 const repos=(data?.repos||[]).filter(r=>`${r.fullName} ${r.description||''}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='private'?r.private:!r.private)));
 const local=projects.filter(p=>p.repository?.toLowerCase()===selected?.fullName.toLowerCase());
 return <div className="github-page"><section className="card github-account"><Github size={32}/><div><h2>{data?.user.name||data?.user.login||'Ton espace GitHub'}</h2><p>{data?`@${data.user.login} · ${data.repos.length} dépôts chargés`:'Connexion via le compte GitHub enregistré dans Git Credential Manager sur ce PC.'}</p></div><button className="button secondary" disabled={loading} onClick={()=>load()}><RefreshCw size={15}/>Actualiser GitHub</button><a className="button primary" href="https://github.com/new" target="_blank" rel="noreferrer">Créer un dépôt<ExternalLink size={15}/></a></section>
 {error&&<div className="card card-pad"><p className="inline-error" role="alert">{error}</p><p>Si aucun compte n’est enregistré, connecte Git à GitHub avec Git Credential Manager depuis le terminal. Aucun jeton n’est envoyé à l’interface.</p><button className="button secondary" disabled={loading} onClick={()=>load()}>Réessayer</button></div>}
 <div className="github-layout"><section className="card github-repositories"><div className="github-filters"><label><Search size={16}/><input aria-label="Rechercher un dépôt" placeholder="Rechercher parmi les dépôts chargés…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Visibilité des dépôts" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tous</option><option value="private">Privés</option><option value="public">Publics</option></select></div>{loading&&!data&&<p role="status">Chargement des dépôts…</p>}{!loading&&data&&!repos.length&&<p>Aucun dépôt ne correspond à ta recherche.</p>}{repos.map(repo=><button key={repo.id} className={`github-repo ${selected?.id===repo.id?'selected':''}`} onClick={()=>setSelected(repo)}><strong>{repo.fullName}</strong><span>{repo.description||'Aucune description'}</span><small>{repo.private?'Privé':'Public'}{repo.archived?' · Archivé':''} · {repo.language||'Sans langage principal'} · ★ {repo.stars}</small></button>)}{data?.hasMore&&<button className="button secondary" disabled={loading} onClick={()=>load(data.page+1)}>{loading?'Chargement…':'Charger les dépôts suivants'}</button>}</section>
 <section className="card github-detail">{!selected?<div className="empty"><Github size={40}/><h3>Sélectionne un dépôt</h3><p>Retrouve son activité et les actions disponibles pour tes projets locaux.</p></div>:<><header><h2>{selected.fullName}</h2><p>{selected.description}</p><p className="github-meta"><GitBranch size={15}/>{selected.branch} <Star size={15}/>{selected.stars}</p><a className="button secondary" href={`https://github.com/${selected.fullName}`} target="_blank" rel="noreferrer">Ouvrir sur GitHub<ExternalLink size={15}/></a></header><div className="github-local">{local.length?local.map(project=><div key={project.name}><h3>Projet local · {project.name}</h3><p>{project.branch} · {project.changedFiles.length} fichier(s) modifié(s)</p><div className="github-actions">{[['deploy','Push GitHub',Upload],['release','Publier une release',Rocket],['terminal','Terminal',Terminal],['vscode','VS Code',Code2]].map(([action,label,Icon])=><button className="button secondary small" key={action} onClick={()=>projectAction(project,action)}><Icon size={14}/>{label}</button>)}</div></div>):<p>Aucun projet de ton dossier de développement n’est associé à ce dépôt.</p>}</div><div className="github-tabs" role="tablist" aria-label="Activité GitHub">{Object.entries(tabs).map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div><div role="tabpanel">{detailError?<p className="inline-error">{detailError}</p>:!details?<p role="status">Chargement de l’activité…</p>:details.errors[tab]?<p className="inline-error">{details.errors[tab]}</p>:<>{!details[tab].length&&<p>Aucun élément à afficher.</p>}{details[tab].map(item=><a className="github-activity" href={safeLink(item.url)} target="_blank" rel="noreferrer" key={item.id}><span><strong>{item.number?`#${item.number} · `:''}{item.title}</strong><small>{item.state} · {new Date(item.updatedAt).toLocaleDateString('fr-FR')}</small></span><ExternalLink size={15}/></a>)}</>}<a className="text-link" href={`https://github.com/${selected.fullName}/${tab==='runs'?'actions':tab}`} target="_blank" rel="noreferrer">Tout voir sur GitHub ↗</a></div></>}</section></div></div>;
}
