import React,{useEffect,useRef,useState} from 'react';
import {Monitor,Plus,Link2,Maximize,Power} from 'lucide-react';
import './remote.css';
const blank={name:'',host:'',port:3389,username:'',domain:'',clipboard:false};
export default function RemoteDesktop({suspended,notice}) {
 const [scan,setScan]=useState({devices:[],total:0,completed:0,running:false});
 const bridge=window.remoteDesktop,slot=useRef(),[state,setState]=useState({profiles:[],phase:'idle',activeId:null}),[draft,setDraft]=useState(blank),[password,setPassword]=useState(''),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false);
 async function run(action,...args){if(!bridge)return;setBusy(true);try{const result=await bridge[action](...args);if(result)setState(result);return true;}catch(e){notice(e.message,'error');return false;}finally{setBusy(false);}}
 useEffect(()=>{if(!bridge)return;bridge.status().then(setState).catch(e=>notice(e.message,'error'));const stop=bridge.onStatus(setState);return()=>{stop();bridge.disconnect().catch(()=>{});};},[]);
 useEffect(()=>{
   if(!bridge||!slot.current)return;
   const layout=()=>{const rect=slot.current.getBoundingClientRect();bridge.layout({visible:!suspended&&!document.hidden,rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height}});};
   const observer=new ResizeObserver(layout);observer.observe(slot.current);window.addEventListener('resize',layout);window.addEventListener('scroll',layout,true);document.addEventListener('visibilitychange',layout);layout();
   return()=>{observer.disconnect();window.removeEventListener('resize',layout);window.removeEventListener('scroll',layout,true);document.removeEventListener('visibilitychange',layout);bridge.layout({visible:false});};
 },[state.activeId,suspended]);
 useEffect(()=>{if(!bridge?.onScan)return;bridge.scanStatus().then(setScan).catch(()=>{});const stop=bridge.onScan(setScan);return()=>{stop();bridge.cancelScan().catch(()=>{});};},[]);
 async function selectDevice(device){setBusy(true);try{let profile=state.profiles.find(p=>p.host===device.host&&p.port===3389);if(!profile){const next=await bridge.save({...blank,name:device.name,host:device.host});setState(next);profile=next.profiles.find(p=>p.host===device.host);}setSelected(profile.id);setPassword('');}catch(e){notice(e.message,'error');}finally{setBusy(false);}}
 const active=state.profiles.find(p=>p.id===state.activeId);
 return <div className="remote-page"><section className="remote-intro"><Monitor size={26}/><div><h2>Tes ordinateurs, dans ton espace.</h2><p>Connexion RDP directe avec le client Windows intégré. Aucun logiciel supplémentaire à installer sur ce PC.</p></div></section>
 {!bridge&&<p className="inline-error">Ouvre l’application Windows pour utiliser le bureau distant intégré.</p>}
 <section className="card workspace-panel"><h2>Appareils de mon réseau</h2><p>Recherche à la demande sur les réseaux privés connectés : port RDP 3389, jusqu’à 254 adresses par interface (4 interfaces maximum). Une réponse RDP ne garantit pas les droits de connexion.</p><button className="button primary" disabled={!bridge||scan.running} onClick={()=>bridge.scan().then(setScan).catch(e=>notice(e.message,'error'))}>Scanner mon réseau</button>{scan.running&&<button className="button secondary" onClick={()=>bridge.cancelScan()}>Arrêter</button>}{scan.total>0&&<p role="status">{scan.running?'Recherche…':scan.cancelled?'Recherche arrêtée':'Recherche terminée'} · {scan.completed}/{scan.total} adresses vérifiées · {scan.devices.length} appareil(s) RDP</p>}{scan.devices.map(device=><article className="workspace-row" key={device.host}><div><strong>{device.name}</strong><small>{device.host}:3389 · {device.network}</small></div><button className="button secondary" disabled={busy} onClick={()=>selectDevice(device)}>Se connecter</button></article>)}{scan.total>0&&!scan.running&&!scan.devices.length&&<p>Aucun appareil RDP détecté. Vérifie que le Bureau à distance est activé et autorisé par le pare-feu du PC cible.</p>}<p>Les accès VPS et ports personnalisés restent disponibles par ajout manuel.</p></section>
 <div className="remote-config"><section className="card workspace-panel"><h2>Mes PC & VPS</h2>{!state.profiles.length&&<p>Ajoute un ordinateur pour créer ton premier accès.</p>}{state.profiles.map(p=><article key={p.id} className="workspace-row"><div><strong>{p.name}</strong><small>{p.host}:{p.port} · {p.username||'Compte non renseigné'}</small></div><button className="button secondary small" disabled={busy} onClick={()=>{setSelected(p.id);setPassword('');}}><Link2 size={14}/>Choisir</button><button className="text-link" onClick={()=>setDraft(p)}>Modifier</button><button className="text-link" disabled={busy} onClick={()=>run('remove',p.id)}>Retirer</button></article>)}{selected&&state.profiles.some(p=>p.id===selected)&&<form className="rdp-login" onSubmit={async e=>{e.preventDefault();const secret=password;setPassword('');if(!await run('save',state.profiles.find(p=>p.id===selected)))return;if(await run('connect',selected,secret)){setTimeout(()=>slot.current?.scrollIntoView({behavior:'smooth',block:'start'}),100);}}}><h3>Connexion · {state.profiles.find(p=>p.id===selected)?.name}</h3><label>Compte distant<input value={state.profiles.find(p=>p.id===selected)?.username||''} onChange={e=>setState({...state,profiles:state.profiles.map(p=>p.id===selected?{...p,username:e.target.value}:p)})}/></label><label>Mot de passe du compte distant<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} maxLength={4096}/><small>Utilisé uniquement pour cette connexion, jamais enregistré.</small></label><button className="button primary" disabled={busy||!bridge}>Ouvrir le bureau</button></form>}</section><section className="card workspace-panel"><h2>{draft.id?'Modifier le profil':'Nouvel ordinateur'}</h2><form onSubmit={async e=>{e.preventDefault();if(await run('save',draft))setDraft(blank);}}>{[['Nom','name','Mon VPS'],['Adresse IP ou nom DNS','host','192.168.1.20'],['Compte distant','username','Administrateur'],['Domaine (facultatif)','domain','']].map(([label,key,placeholder])=><label key={key}>{label}<input required={key==='name'||key==='host'} maxLength={key==='host'?253:200} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} placeholder={placeholder}/></label>)}<label>Port RDP<input type="number" min="1" max="65535" value={draft.port} onChange={e=>setDraft({...draft,port:Number(e.target.value)})}/></label><label className="check-label"><input type="checkbox" checked={draft.clipboard} onChange={e=>setDraft({...draft,clipboard:e.target.checked})}/>Partager le presse-papiers avec cet ordinateur</label><button className="button primary" disabled={busy||!bridge}><Plus size={15}/>Enregistrer le profil</button></form></section></div>
 {state.activeId&&<section className="remote-session"><header><span><i className={state.phase==='connected'?'live-dot':'neutral-dot'}/><strong>{active?.name}</strong> · {({loading:'Préparation',connecting:'Connexion…',connected:'Connecté',disconnected:'Déconnecté',error:'Erreur'})[state.phase]}</span><div><button title="Plein écran de l’application" aria-label="Plein écran" onClick={()=>run('fullscreen')}><Maximize size={16}/></button><button onClick={()=>run('focus')}>Clavier distant</button><button onClick={()=>run('disconnect')}><Power size={15}/>Fermer la connexion</button></div></header><div className="remote-native-slot" ref={slot}><p>{state.message||'Préparation du bureau distant…'}</p></div><footer>Ctrl + Alt + Fin : écran de sécurité distant. Ctrl + Alt + Flèche gauche : libérer le clavier. Quitter cette page déconnecte la session sans éteindre l’ordinateur.</footer></section>}
 <details className="card workspace-panel"><summary>Préparer le PC distant</summary><p>Active le Bureau à distance sur le PC/VPS cible et autorise ton compte à s’y connecter. Il doit être joignable depuis ce PC, directement sur ton réseau ou via ton VPN. Le client ne modifie pas le pare-feu et n’active pas RDP à ta place.</p><p>Windows peut afficher une confirmation du certificat du serveur. Le partage des disques et imprimantes est désactivé ; le presse-papiers s’active profil par profil.</p></details></div>;
}
