import React,{useState} from 'react';
import {api} from './api';
import './workspace.css';

export const widgetNames={codex:'Activité Codex',launchers:'Raccourcis',stats:'État du PC',servers:'Serveurs',music:'Spotify',projects:'Projets',activity:'Activité',terminal:'Terminal'};
const date=value=>value?new Date(value).toLocaleString('fr-FR'):'Sans date';
const emptyPost={title:'',account:'',body:'',status:'idea',date:'',metrics:{}};
function Panel({title,children}){return <section className="card workspace-panel"><h2>{title}</h2>{children}</section>;}

export default function WorkspacePage({data,refresh,notice,projects,accounts,navigate,openTerminal,onSettings,initialTab='sessions'}) {
 const [tab,setTab]=useState(initialTab),[busy,setBusy]=useState(false),[post,setPost]=useState(emptyPost),[mode,setMode]=useState({name:'',project:'',stack:false,editor:true,music:false,terminal:true}),[site,setSite]=useState({name:'',url:''}),[command,setCommand]=useState({name:'',command:''}),[password,setPassword]=useState(''),[backup,setBackup]=useState(''),[confirm,setConfirm]=useState(''),[filter,setFilter]=useState(''),[feed,setFeed]=useState(''),[update,setUpdate]=useState(null);
 async function run(fn){setBusy(true);try{await fn();await refresh();}catch(e){notice(e.message,'error');}finally{setBusy(false);}}
 const save=(kind,value,done)=>run(async()=>{await api('/workspace/'+kind+'/save',value);done?.();notice('Enregistré.');});
 const remove=(kind,id)=>run(()=>api('/workspace/'+kind+'/remove',{id}));
 const prefs=value=>run(()=>api('/workspace/preferences',value));
 async function start(s){await run(async()=>{const result=await api('/workspace/sessions/'+s.id+'/run',{});if(result.terminal)openTerminal(result.project);notice('Session lancée. Les étapes sont visibles dans le journal.');});}
 const field=(label,key,value,set,type='text')=><label>{label}<input type={type} value={value[key]||''} onChange={e=>set({...value,[key]:e.target.value})} required/></label>;
 const tabs={sessions:'Sessions',notifications:'Notifications',health:'Surveillance',creator:'Studio créateur',home:'Mon accueil',commands:'Commandes',backup:'Sauvegardes',updates:'Mises à jour',discord:'Journal Discord'};
 return <div className="workspace-page"><div className="workspace-tabs" role="tablist">{Object.entries(tabs).map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)}>{label}{id==='notifications'&&data.notifications.some(n=>!n.read)?' •':''}</button>)}</div>
 {tab==='sessions'&&<div className="workspace-columns"><Panel title="Tes modes de session"><p>Choisis les outils à préparer en un clic. MySQL démarre avant FiveM.</p>{data.sessions.map(s=><article className="workspace-row" key={s.id}><div><strong>{s.name}</strong><small>{[s.project,s.stack&&'MySQL + FiveM',s.music&&'Spotify',s.terminal&&'Terminal'].filter(Boolean).join(' · ')}</small></div><button disabled={busy} onClick={()=>start(s)}>Lancer</button><button onClick={()=>setMode(s)}>Modifier</button><button disabled={busy} onClick={()=>remove('sessions',s.id)}>Supprimer</button></article>)}</Panel><Panel title={mode.id?'Modifier la session':'Nouvelle session'}><form onSubmit={e=>{e.preventDefault();save('sessions',mode,()=>setMode({name:'',project:'',stack:false,editor:true,music:false,terminal:true}));}}>{field('Nom','name',mode,setMode)}<label>Projet<select value={mode.project} onChange={e=>setMode({...mode,project:e.target.value})}><option value="">Aucun projet</option>{projects.map(p=><option key={p.name}>{p.name}</option>)}</select></label>{[['stack','Démarrer MySQL et FiveM'],['editor','Ouvrir le projet dans VS Code'],['music','Reprendre Spotify'],['terminal','Ouvrir le terminal']].map(([id,label])=><label className="check-label" key={id}><input type="checkbox" checked={mode[id]} onChange={e=>setMode({...mode,[id]:e.target.checked})}/>{label}</label>)}<button disabled={busy} className="button primary">Enregistrer</button></form></Panel></div>}
 {tab==='notifications'&&<Panel title="Centre de notifications"><div className="workspace-actions"><button disabled={busy} onClick={()=>run(()=>api('/workspace/read',{}))}>Tout marquer comme lu</button><label className="check-label"><input type="checkbox" checked={data.quiet} onChange={e=>prefs({quiet:e.target.checked})}/>Mode silencieux · conserver le journal sans alerte</label></div><p>Opérations, incidents et actions des intégrations. Les notifications personnelles TikTok, Instagram et Discord restent dans leurs espaces officiels.</p>{!data.notifications.length&&<p>Aucune notification pour le moment.</p>}{data.notifications.map(n=><article className={'workspace-row '+(!n.read?'unread':'')} key={n.id}><span className={'status-dot '+n.type}/><div><strong>{n.message}</strong><small>{date(n.time)} · {n.read?'Lu':'Non lu'}</small></div></article>)}</Panel>}
 {tab==='health'&&<><div className="workspace-actions"><button disabled={busy} onClick={()=>run(()=>api('/workspace/check',{}))}>Vérifier maintenant</button><span>Actualisation toutes les minutes tant que l’application reste ouverte.</span></div><div className="health-grid">{Object.values(data.health).map(h=><Panel key={h.id} title={h.name}><span className={'health-status '+h.status}>{({up:'Disponible',down:'Arrêté / indisponible',unknown:'État inconnu',pending:'En cours'})[h.status]}</span><p>{h.detail} {h.latency!=null&&'· '+h.latency+' ms'}</p><small>{date(h.checkedAt)}</small></Panel>)}</div><div className="workspace-columns"><Panel title="Sites surveillés"><form onSubmit={e=>{e.preventDefault();save('monitors',site,()=>setSite({name:'',url:''}));}}>{field('Nom','name',site,setSite)}{field('Adresse HTTP ou HTTPS','url',site,setSite,'url')}<button disabled={busy}>Ajouter</button></form>{data.monitors.map(s=><div className="workspace-row" key={s.id}><div><strong>{s.name}</strong><small>{s.url}</small></div><button disabled={busy} onClick={()=>remove('monitors',s.id)}>Retirer</button></div>)}</Panel><Panel title="Historique des changements">{!data.incidents.length&&<p>Aucun changement détecté.</p>}{data.incidents.map(i=><div className="workspace-row" key={i.id}><div><strong>{i.name} · {i.status==='up'?'Rétabli':i.detail||'Arrêté'}</strong><small>{date(i.time)}</small></div></div>)}</Panel></div></>}
 {tab==='creator'&&<div className="workspace-columns"><Panel title="Calendrier & idées"><label>Filtrer par compte<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tous les comptes</option>{accounts.map(a=><option key={a.id} value={a.id}>@{a.handle}</option>)}</select></label><p>Planifie tes publications et garde tes brouillons. Les statistiques ci-dessous sont tes relevés manuels ; les chiffres en direct sont dans « Mes réseaux ».</p><button onClick={()=>navigate('social')}>Ouvrir les statistiques officielles</button>{data.posts.filter(p=>!filter||p.account===filter).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')).map(p=><article className="workspace-row" key={p.id}><div><strong>{p.title}</strong><small>{date(p.date)} · {accounts.find(a=>a.id===p.account)?.handle||'Sans compte'} · {({idea:'Idée',draft:'Brouillon',planned:'Planifié',published:'Publié'})[p.status]}</small><small>{Object.entries(p.metrics||{}).map(([k,v])=>`${({views:'vues',likes:'j’aime',comments:'commentaires',followers:'abonnés'})[k]} : ${v}`).join(' · ')}</small></div><button onClick={()=>setPost({...p,date:p.date?new Date(new Date(p.date)-new Date(p.date).getTimezoneOffset()*60000).toISOString().slice(0,16):''})}>Modifier</button><button disabled={busy} onClick={()=>remove('posts',p.id)}>Supprimer</button></article>)}</Panel><Panel title={post.id?'Modifier le contenu':'Nouveau contenu'}><form onSubmit={e=>{e.preventDefault();save('posts',post,()=>setPost(emptyPost));}}>{field('Titre','title',post,setPost)}<label>Compte<select required value={post.account} onChange={e=>setPost({...post,account:e.target.value})}><option value="">Choisir</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.platform} · @{a.handle}</option>)}</select></label><label>Statut<select value={post.status} onChange={e=>setPost({...post,status:e.target.value})}>{Object.entries({idea:'Idée',draft:'Brouillon',planned:'Planifié',published:'Publié'}).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Date prévue<input type="datetime-local" value={post.date} onChange={e=>setPost({...post,date:e.target.value})}/></label><label>Brouillon<textarea rows={5} value={post.body} onChange={e=>setPost({...post,body:e.target.value})}/></label><details><summary>Relevé de performances manuel</summary>{Object.entries({views:'Vues',likes:'J’aime',comments:'Commentaires',followers:'Abonnés'}).map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={post.metrics?.[key]??''} onChange={e=>setPost({...post,metrics:{...post.metrics,[key]:e.target.value}})}/></label>)}</details><button className="button primary" disabled={busy}>Enregistrer</button></form></Panel></div>}
 {tab==='home'&&<div className="workspace-columns"><Panel title="Organiser les widgets"><p>Utilise les flèches pour déplacer un bloc, ou masque-le.</p>{data.widgets.map((id,i)=><div className="workspace-row" key={id}><strong>{widgetNames[id]}</strong><button disabled={busy||i===0} onClick={()=>{const widgets=[...data.widgets];[widgets[i-1],widgets[i]]=[widgets[i],widgets[i-1]];prefs({widgets});}}>↑</button><button disabled={busy||i===data.widgets.length-1} onClick={()=>{const widgets=[...data.widgets];[widgets[i+1],widgets[i]]=[widgets[i],widgets[i+1]];prefs({widgets});}}>↓</button><button disabled={busy} onClick={()=>prefs({widgets:data.widgets.filter(v=>v!==id)})}>Masquer</button></div>)}{Object.keys(widgetNames).filter(id=>!data.widgets.includes(id)).map(id=><button key={id} disabled={busy} onClick={()=>prefs({widgets:[...data.widgets,id]})}>Afficher {widgetNames[id]}</button>)}</Panel><Panel title="Projets favoris">{projects.map(p=><div className="workspace-row" key={p.name}><strong>{p.name}</strong><button disabled={busy} onClick={()=>prefs({favorite:p.name})}>{data.favorites.includes(p.name)?'★ Épinglé':'☆ Épingler'}</button></div>)}</Panel></div>}
 {tab==='commands'&&<div className="workspace-columns"><Panel title="Commandes habituelles"><p>Retrouve ces commandes dans les terminaux. Le clic les insère ; Entrée les exécute.</p>{data.commands.map(c=><div className="workspace-row" key={c.id}><div><strong>{c.name}</strong><code>{c.command}</code></div><button onClick={()=>setCommand(c)}>Modifier</button><button disabled={busy} onClick={()=>remove('commands',c.id)}>Supprimer</button></div>)}</Panel><Panel title="Enregistrer une commande"><form onSubmit={e=>{e.preventDefault();save('commands',command,()=>setCommand({name:'',command:''}));}}>{field('Nom','name',command,setCommand)}{field('Commande PowerShell','command',command,setCommand)}<button disabled={busy}>Enregistrer</button></form></Panel></div>}
 {tab==='backup'&&<Panel title="Sauvegarde chiffrée des paramètres"><p>Les clés restent protégées par ton compte Windows. Cette sauvegarde se restaure sur le même compte Windows ; elle n’inclut pas les cookies de connexion ni les fichiers de tes projets. Une copie des anciens paramètres est conservée à la restauration.</p><label>Mot de passe de la sauvegarde<input type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy||password.length<12} onClick={()=>run(async()=>{const {blob}=await api('/backup/export',{password});const url=URL.createObjectURL(new Blob([blob],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='LeStitcheur-'+new Date().toISOString().slice(0,10)+'.lsfbackup';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setPassword('');notice('Sauvegarde exportée.');})}>Exporter la sauvegarde</button><hr/><label>Charger une sauvegarde<input type="file" accept=".lsfbackup,.json" onChange={async e=>{const f=e.target.files[0];if(f){if(f.size>2*1024*1024){notice('Fichier trop volumineux.','error');return;}setBackup(await f.text());}}}/></label><label>Recopie RESTAURER<input value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button disabled={busy||!backup||!password||confirm!=='RESTAURER'} onClick={()=>run(async()=>{const restored=await api('/backup/restore',{blob:backup,password,confirm});onSettings(restored);setPassword('');setConfirm('');notice('Paramètres restaurés.');})}>Restaurer les paramètres</button></Panel>}
 {tab==='updates'&&<Panel title="Mises à jour de l’application"><p>La source de publication reste à configurer. Publie les fichiers de version sur ton hébergement HTTPS puis renseigne son adresse ici. L’installation attend la fermeture des terminaux et la fin des opérations.</p><label>Adresse HTTPS du dossier de publication<input type="url" placeholder="https://ton-domaine.fr/updates/" value={feed} onChange={e=>setFeed(e.target.value)}/></label><div className="workspace-actions"><button disabled={busy||!window.panelUpdates} onClick={()=>run(async()=>{const s=await window.panelUpdates.status();setFeed(s.feed||'');setUpdate(s);})}>Lire la configuration</button><button disabled={busy||!window.panelUpdates} onClick={()=>run(async()=>setUpdate(await window.panelUpdates.configure(feed)))}>Enregistrer la source</button><button disabled={busy||!window.panelUpdates} onClick={()=>run(async()=>setUpdate(await window.panelUpdates.check()))}>Rechercher une version</button><button disabled={busy||!update?.available} onClick={()=>run(async()=>setUpdate(await window.panelUpdates.download()))}>Télécharger</button><button disabled={busy||!update?.downloaded} onClick={()=>run(()=>window.panelUpdates.install())}>Installer et relancer</button></div>{update&&<><p>{update.message||'Version installée : '+update.current}</p>{update.notes&&<pre>{update.notes}</pre>}</>}{!window.panelUpdates&&<p>Disponible dans l’application Windows.</p>}</Panel>}
 {tab==='discord'&&<Panel title="Actions effectuées via tes bots"><p>Historique local persistant. Les confirmations et motifs restent obligatoires avant l’envoi d’une action.</p>{data.notifications.filter(n=>n.source==='discord').map(n=><article className="workspace-row" key={n.id}><div><strong>{n.message}</strong><small>{date(n.time)} · Motif : {n.details?.reason}</small></div></article>)}{!data.notifications.some(n=>n.source==='discord')&&<p>Aucune action enregistrée depuis cette version.</p>}</Panel>}
 </div>;
}

export function ProjectDetails({projects,openTerminal,openLogs}) {
 return <div className="project-detail-grid">{projects.map(p=><Panel key={p.name} title={p.name}><span className="eyebrow">{p.stack} · {p.branch||'Sans branche Git'}</span><p>{p.lastCommit||'Aucun commit disponible'}</p><details><summary>{p.changedFiles?.length||0} fichier(s) modifié(s){p.changedFiles?.length===100?' ou plus':''}</summary><pre>{p.changedFiles?.join('\n')||'Dossier propre'}</pre></details><div className="workspace-actions"><button onClick={()=>openTerminal(p.name)}>Terminal / lancer le projet</button><button onClick={()=>openLogs(p.name)}>Journaux</button>{p.scripts.filter(s=>['dev','start'].includes(s)).map(script=><button key={script} onClick={()=>openTerminal(p.name,'npm run '+script+'\r')}>Lancer {script}</button>)}{p.siteUrl&&<a href={p.siteUrl} target="_blank" rel="noreferrer">Ouvrir le site ↗</a>}</div>{p.scripts.length>0&&<p>Scripts disponibles : {p.scripts.join(', ')}</p>}</Panel>)}</div>;
}
